app_version: "0.0.1"
app_name: "tenant-api"
app_port: 9000
app_url: "http://localhost"
environment: "development"
jwt_secret: ""
rabbitmq:
  url: amqp://user:pass@localhost:5672/
database:
  url: postgres://user:pass@localhost:5432/app
workers: 3 # Default worker
